# docker compose -f "docker-compose.yml" up -d --build
# docker-desktop://dashboard/build/desktop-linux/desktop-linux/t91lkq0fas563p72pouhbrwsq
services:
  node-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: node-app
    env_file:
      - .env
    environment:
      DEPLOY_ENV: Docker
      NODE_ENV: production
      MONGODB_URL: mongodb://mongodb:27017/employee-checks
    ports:
      - "7384:7384"
    depends_on:
      - mongodb
    container_name: docker_employee_checks
    volumes:
      - image-storage:/usr/src/employees_pointage
    networks:
      - employee-network

  mongodb:
    image: mongo:4.2.1-bionic
    container_name: docker_mongodb
    ports:
      - "21018:27017"
    volumes:
      - dbdata:/data/db
      - configdb:/data/configdb
    networks:
      - employee-network

volumes:
  image-storage:
  dbdata:
    driver: local
  configdb:

networks:
  employee-network:
    driver: bridge
