name: Deploy to AWS Fargate

on:
  push:
    tags:
      - "fg[0-9]+.[0-9]+.[0-9]+*" # Trigger on fg tags
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        run: |
          docker build -t my-ecr-repo .

          IMAGE_URI=381491864469.dkr.ecr.eu-north-1.amazonaws.com/employee-webservice
          docker build -t $REPO_NAME .
          docker tag $REPO_NAME:latest $IMAGE_URI:latest
          docker push $IMAGE_URI:latest
